import { FrameworkFrontendImpl } from '../frameworkimpl'
import BackBtn from './BackBtn'
import './styles/content.css'

interface ShowVisProps {
  framework: FrameworkFrontendImpl
  updateStage: (s: string) => void
}

/**
 * @param props The front-end framework and a means to update the front-end stage.
 * @returns Div that is to be displayed when a visualization is selected. The
 * render for the visualization is generated by the selected plugin.
 */
const ShowVis: (props: ShowVisProps) => JSX.Element = (props: ShowVisProps) => {
  const pluginName = props.framework.getCurrVisPluginName()
  const pluginDescription = props.framework.getCurrVisPluginDescription()

  return (
    <div id='input-data' className='content-wrapper'>
      <BackBtn updateStage={props.updateStage} />
      <div className='content'>
        <div className='content-title'>Here's the <strong>{pluginName}</strong> for your images!</div>
        <div className='content-descrp'>{pluginDescription}</div>
        <div className='plugin-frontend' id='vis'>
          {props.framework.getVisPluginComponent()}
        </div>
        <button onClick={() => { props.updateStage('visplugin') }}>Try Other Visualizations</button>
      </div>
    </div>
  )
}

export default ShowVis
